const fs = require('fs');

const code = [
  "const path = require('path');",
  "const dotenv = require('dotenv');",
  "const envPath = path.join(__dirname, '../.env');",
  "console.log('📁 .env path:', envPath);",
  "const result = dotenv.config({ path: envPath });",
  "if (result.error) { console.error('❌ .env not found'); process.exit(1); }",
  "console.log('🔍 MONGO_URI:', process.env.MONGO_URI ? '✅ Found' : '❌ Missing');",
  "const express = require('express');",
  "const cors = require('cors');",
  "const mongoose = require('mongoose');",
  "const app = express();",
  "app.use(cors());",
  "app.use(express.json({ limit: '10mb' }));",
  "app.use(express.urlencoded({ extended: true }));",
  "const authRoutes   = require('./routes/authRoutes');",
  "const quizRoutes   = require('./routes/quizRoutes');",
  "const userRoutes   = require('./routes/userRoutes');",
  "const resultRoutes = require('./routes/resultRoutes');",
  "app.use('/api/auth',    authRoutes);",
  "app.use('/api/quizzes', quizRoutes);",
  "app.use('/api/users',   userRoutes);",
  "app.use('/api/results', resultRoutes);",
  "app.get('/api/health', (req, res) => res.json({ status: 'ok', message: 'EduHub API is running' }));",
  "app.use((req, res) => res.status(404).json({ message: 'Route not found' }));",
  "app.use((err, req, res, next) => {",
  "  console.error('Global error:', err.stack);",
  "  if (err.name === 'ValidationError') {",
  "    const messages = Object.values(err.errors).map((e) => e.message);",
  "    return res.status(400).json({ message: messages.join(', ') });",
  "  }",
  "  if (err.code === 11000) {",
  "    const field = Object.keys(err.keyValue)[0];",
  "    return res.status(400).json({ message: 'Duplicate value for ' + field });",
  "  }",
  "  if (err.name === 'CastError') return res.status(400).json({ message: 'Invalid ID format' });",
  "  if (err.name === 'JsonWebTokenError') return res.status(401).json({ message: 'Invalid token' });",
  "  if (err.name === 'TokenExpiredError') return res.status(401).json({ message: 'Token expired' });",
  "  res.status(500).json({ message: 'Internal server error' });",
  "});",
  "const PORT = process.env.PORT || 5000;",
  "const MONGO_URI = process.env.MONGO_URI;",
  "if (!MONGO_URI) {",
  "  console.error('❌ MONGO_URI is undefined — check backend/.env');",
  "  process.exit(1);",
  "}",
  "mongoose.connect(MONGO_URI)",
  "  .then(() => {",
  "    console.log('✅ MongoDB connected successfully');",
  "    app.listen(PORT, () => {",
  "      console.log('🚀 Server running on http://localhost:' + PORT);",
  "      console.log('   Health check → http://localhost:' + PORT + '/api/health');",
  "    });",
  "  })",
  "  .catch((err) => {",
  "    console.error('❌ MongoDB connection error:', err.message);",
  "    process.exit(1);",
  "  });",
  "module.exports = app;"
].join('\n');

fs.writeFileSync('./src/app.js', code);
console.log('✅ app.js written successfully!');
console.log('Lines written:', code.split('\n').length);